# Generated by Django 4.0.3 on 2022-03-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0004_client_access_token_client_last_hit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AddField(
            model_name='oauth',
            name='client_id',
            field=models.CharField(default='law2022', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oauth',
            name='client_secret',
            field=models.CharField(default='2022law', max_length=255),
            preserve_default=False,
        ),
    ]
